#!/usr/bin/env node

const uuidv1 = require('uuid/v1');

const express = require('express');
const app  = express();
const http = require('http').Server(app);
const io   = require('socket.io')(http);
const dirname = __dirname.split("/").splice(0,__dirname.split("/").length-1).join("/");
let games = {};

app.use('/',
	express.static('build', {
	    dotfiles: 'ignore',
	    etag: false,
	    extensions: ['css', 'js', 'html'],
	    index: false,
	    maxAge: '1d',
	    redirect: false,
	    setHeaders: function (res, path, stat) {
		res.set('x-timestamp', Date.now())
	    }
	}));

io.on('connection', (socket) => {
    console.log('a user connected');
    socket.on('join', (game_id) => {
	console.log("join", game_id);
	if(!games[game_id]) {
	    games[game_id] = {
		players: []
	    };
	}
	socket.join(game_id);
	games[game_id].players.push(socket);
	if(games[game_id].players.length == 2) {
	    io.to(game_id).emit('start');
	}
    });
});

http.listen(3000, () => {
    console.log('listening on *:3000');
});
